# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIwqu4sqg4pxiRh4SKI8N72XqMne2Xjr
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload an image
uploaded = files.upload()

# Read the image
filename = next(iter(uploaded))
img = cv2.imread(filename)

# Convert the image from BGR to RGB
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Convert the image to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply histogram equalization
equalized_img = cv2.equalizeHist(gray_img)

# Display original and equalized images
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(gray_img, cmap="gray")
plt.title("Original Grayscale Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(equalized_img, cmap="gray")
plt.title("Histogram Equalized Image")
plt.axis("off")

plt.show()

# Compare histograms
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(gray_img.ravel(), 256, [0, 256], color="blue")
plt.title("Original Histogram")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.subplot(1, 2, 2)
plt.hist(equalized_img.ravel(), 256, [0, 256], color="green")
plt.title("Equalized Histogram")
plt.xlabel("Pixel Intensity")
plt.ylabel("Frequency")

plt.show()

# Save the equalized image
cv2.imwrite("equalized_image.jpg", equalized_img)

# Download the result
files.download("equalized_image.jpg")