# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIwqu4sqg4pxiRh4SKI8N72XqMne2Xjr
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload an image
uploaded = files.upload()

# Read the image
filename = next(iter(uploaded))
img = cv2.imread(filename)

# Convert BGR to RGB for displaying
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Function to analyze color histogram
def analyze_histogram(image):
    colors = ('b', 'g', 'r')
    labels = ('Blue', 'Green', 'Red')

    plt.figure(figsize=(10, 5))

    for color, label, channel in zip(colors, labels, range(3)):
        histogram = cv2.calcHist(
            [image], [channel], None, [256], [0, 256]
        )
        plt.plot(histogram, color=color, label=label)

    plt.title("Color Histogram")
    plt.xlabel("Pixel Intensity (0-255)")
    plt.ylabel("Number of Pixels")
    plt.xlim([0, 256])
    plt.legend()
    plt.grid(True)
    plt.show()

# Display the original image
plt.figure(figsize=(5, 4))
plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis("off")
plt.show()

# Analyze the histogram
analyze_histogram(img)

# Save the histogram plot as an image
plt.figure(figsize=(10, 5))

for color, label, channel in zip(
    ('b', 'g', 'r'), ('Blue', 'Green', 'Red'), range(3)
):
    histogram = cv2.calcHist([img], [channel], None, [256], [0, 256])
    plt.plot(histogram, color=color, label=label)

plt.title("Color Histogram")
plt.xlabel("Pixel Intensity (0-255)")
plt.ylabel("Number of Pixels")
plt.xlim([0, 256])
plt.legend()
plt.grid(True)
plt.savefig("color_histogram.png")
plt.show()

files.download("color_histogram.png")