# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIwqu4sqg4pxiRh4SKI8N72XqMne2Xjr
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload an image
uploaded = files.upload()

# Read the image
filename = next(iter(uploaded))
img = cv2.imread(filename)

# Convert BGR to RGB for display
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Apply Gaussian Blur
blur_img = cv2.GaussianBlur(img, (15, 15), 0)

# Convert blurred image to RGB
blur_rgb = cv2.cvtColor(blur_img, cv2.COLOR_BGR2RGB)

# Display original and blurred images
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(blur_rgb)
plt.title("Gaussian Blurred Image")
plt.axis("off")

plt.show()

# Save the blurred image
cv2.imwrite("blurred_image.jpg", blur_img)

# Download the blurred image
files.download("blurred_image.jpg")